---
- name: Update Ansible Inventory
  shell: |
    cat <<EOF >> /opt/ansible/inventory

    [master]
    {{ masternode }}

    [workers]
    {{ workernode1 }}

    [k8s:children]
    master
    workers

    [k8s:vars]
    ansible_user={{ ansible_user }}
    ansible_password={{ ansible_password }}
    ansible_become_pass={{ ansible_become_pass }}
  when: ansible_host == localhost

- meta: refresh_inventory
  when: ansible_host == localhost

- name: Configure SSH
  include_tasks: ssh_config.yaml
