---
- name: Build Kubernetes Cluster
  hosts: localhost
  #vars:
  #  masternode: kube01.lab.local
  #  workernode1: kube02.lab.local
  #  ansible_user: xadmin
  #  ansible_password: password
  #  ansible_become_pass: password
  #  k8s_version: 1.19.16-00
  tasks:

  - name: Load Variables
    include_vars:
      file: /opt/ansible/roles/kubernetes/vars/main.yml

  - name: Update Ansible Inventory
    shell: |
      cat <<EOF >> /opt/ansible/inventory

      [master]
      {{ masternode }}

      [workers]
      {{ workernode1 }}

      [k8s:children]
      master
      workers

      [k8s:vars]
      ansible_user={{ ansible_user }}
      ansible_password={{ ansible_password }}
      ansible_become_pass={{ ansible_become_pass }}

#      [master]
#      kube01.lab.local
#
#      [workers]
#      kube02.lab.local
#
#      [k8s:children]
#      master
#      workers
#
#      [k8s:vars]
#      ansible_user=xadmin
#      ansible_password=password
#      ansible_become_pass=password

  - meta: refresh_inventory

- name: Initialize Instances
  hosts: k8s
  roles:
    - kubernetes
