---
- name: Build Kubernetes Cluster
  hosts: localhost
  tasks:

  - name: Load Variables
    include_vars:
      file: /opt/ansible/roles/kubernetes/vars/main.yml

  - name: Update Ansible Inventory
    shell: |
      cat <<EOF >> /opt/ansible/inventory

      [master]
      {{ masternode }}

      [workers]
      {{ workernode1 }}

      [k8s:children]
      master
      workers

      [k8s:vars]
      ansible_user={{ ansible_user }}
      ansible_password={{ ansible_password }}
      ansible_become_pass={{ ansible_become_pass }}

  - meta: refresh_inventory

- name: Initialize Instances
  hosts: k8s
  roles:
    - kubernetes
